---
- hosts: node_exporter
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: prometheus
  become: true
  become_user: root
  become_method: sudo
  roles:
    - prometheus_blackbox_exporter
    - prometheus
    - grafana
